#welcome examples
server:
  port: 18081
#JSP config
  servlet:
    jsp:
      init-parameters:
        development: true
#custume error page
  error:
    whitelabel:
      enabled: false
 
#db config
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    hikari:
      jdbc-url: jdbc:oracle:thin:@localhost:1521/xe
      pool-name: hikari-cp
      maximum-pool-size: 30
      minimum-idle: 2
      #driver-class-name: oracle.jdbc.driver.OracleDriver
      driver-class-name: oracle.jdbc.OracleDriver
      username: hr
      password: hr
