Free Board Posts

CREATE TABLE FB_POST_DATA (
    SEQ NUMBER(30) NOT NULL PRIMARY KEY,
    ID VARCHAR2(255) NOT NULL,
    TITLE VARCHAR2(255) NOT NULL,
    CONTENT VARCHAR2(4000) NOT NULL,
    POST_DATE DATE DEFAULT SYSDATE,
    DEL NUMBER(10) NOT NULL,
    READCOUNT NUMBER(30) NOT NULL
);

CREATE SEQUENCE FB_POST_DATA_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOCACHE;

SELECT * FROM FB_POST_DATA;
SELECT FB_POST_DATA_SEQ.CURRVAL FROM DUAL;

INSERT INTO FB_POST_DATA VALUES(
    FB_POST_DATA_SEQ.NEXTVAL, 
    'admin',
    'test title 1',
    'testtesttesttesttesttest11testtesttesttesttest22testtesttesttesttesttest11testtesttesttesttest22',
    SYSDATE,
    1,
    0
);