
spring:

  # ORM config
  jpa:
    hibernate:
      ddl-auto: create

  # MySQL config
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: hr
    password: hr
    hikari:
      pool-name: hikari-cp
      maximum-pool-size: 30
      minimum-idle: 2
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

  # Redis config
#  redis:
#    host: 127.0.0.1
#    port: 16379
#    database: 1
#    lettuce:
#      pool:
#        max-active: 10
#        max-idle: 10
#        min-idle: 0

  thymeleaf:
    cache: false
    enabled: true
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html


server:

  port: 18080